=== Qligent-Corp/libatsc3/specs/atsc3/schemas/S33-1-1070r0-schemasFor-A331-2019-20190208-1/DWD-1.0-20180830.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dwd="tag:atsc.org,2016:XMLSchemas/ATSC3/AppSignaling/DWD/1.0/" targetNamespace="tag:atsc.org,2016:XMLSchemas/ATSC3/AppSignaling/DWD/1.0/" elementFormDefault="qualified">
	<xs:element name="DWD" type="dwd:DWDType"/>
	<xs:complexType name="DWDType">
		<xs:sequence>
			<xs:element name="DistributionWindow" type="dwd:DistributionWindowType" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="DistributionWindowType">
		<xs:sequence>
			<xs:element name="AppContextId" type="dwd:AppContextIdType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="contentLabel" type="xs:unsignedInt"/>
		<xs:attribute name="startTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="endTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="lctTSIRef" type="dwd:listOfUnsignedInt" use="required"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="AppContextIdType">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:attribute name="dwFilterCode" type="dwd:listOfUnsignedInt"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="listOfUnsignedInt">
		<xs:list itemType="xs:unsignedInt"/>
	</xs:simpleType>
</xs:schema>

=== Qligent-Corp/libatsc3/specs/atsc3/schemas/S33-1-1070r0-schemasFor-A331-2019-20190208-1/DWD-Example2-20180830.xml
<?xml version="1.0" encoding="UTF-8"?>
<DWD xmlns="tag:atsc.org,2016:XMLSchemas/ATSC3/AppSignaling/DWD/1.0/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="tag:atsc.org,2016:XMLSchemas/ATSC3/AppSignaling/DWD/1.0/ DWD-1.0-20180830.xsd">
	<DistributionWindow contentLabel="1" startTime="2016-07-17T12:00:47Z" endTime="2016-07-18T12:00:47Z" lctTSIRef="43 44">
		<AppContextId>A.xyz.com</AppContextId>
	</DistributionWindow>
	<DistributionWindow contentLabel="2" startTime="2016-07-18T12:00:47Z" endTime="2016-07-19T12:00:47Z" lctTSIRef="43 44">
		<AppContextId>A.xyz.com</AppContextId>
	</DistributionWindow>
	<DistributionWindow contentLabel="1" startTime="2016-07-19T12:00:47Z" endTime="2016-07-20T12:00:47Z" lctTSIRef="43 44">
		<AppContextId>A.xyz.com</AppContextId>
	</DistributionWindow>
		<DistributionWindow contentLabel="2" startTime="2016-07-20T12:00:47Z" endTime="2016-07-21T12:00:47Z" lctTSIRef="43 44">
		<AppContextId>A.xyz.com</AppContextId>
	</DistributionWindow>
</DWD>
